DROP TABLE IF EXISTS USERS;
CREATE SEQUENCE user_seq;
CREATE TABLE USERS(
                    ID INTEGER DEFAULT nextval('user_seq') PRIMARY KEY,
                    NAME varchar(40) NOT NULL,
                    PASSWORD varchar(60),
                    ACTIVE BOOLEAN NOT NULL,
                    UUID varchar(36),
                    LAST_LOGIN TIMESTAMP
);


INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE, UUID) VALUES (0, 'Demo', '1234', '2011-01-01 15:00:00', TRUE, '7dc53df5-703e-49b3-8670-b1c468f47f1f');
INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE) VALUES (1, 'Admin', 'admin', '2011-01-01 16:00:00', TRUE);
INSERT INTO USERS (ID, NAME, PASSWORD, LAST_LOGIN, ACTIVE) VALUES (2, 'User', 'user', '2011-01-01 17:00:00', TRUE);


ALTER SEQUENCE user_seq RESTART WITH 100;